#!/usr/bin/env python
import sys, argparse, pexpect, os, getpass

####################################
########## Configurations ##########
####################################
username='yourUserName'
host='ssh.ece.ubc.ca'
password=None

####################################
############ getPapers #############
####################################

# Receive input arguments
parser = argparse.ArgumentParser(description='Download papers from IEEE Xplore')
parser.add_argument('URL', metavar='URL', type=str, 
                   help='URL of IEEE Xplore paper')
parser.add_argument('--username', dest='username', default=username,
                   help='The account you want to access in the remote host')
parser.add_argument('--host', dest='host', default=host,
                   help='Remote host you want to ssh into to download the papers')
args = parser.parse_args()

# Check whether the URL is from IEEE
if "ieeexplore.ieee.org/document/" in args.URL:
	paper_id = args.URL.split("document/")[1].split("/")[0]
	association = 'IEEE'
else:
	print("The URL you entered doesn't seem to be from IEEE Xplore")
	exit()
paper_name=association+"_"+paper_id+".pdf"

# Get user password if not defined
if password is None:
	password = getpass.getpass(prompt="Password for "+args.username+"@"+args.host+": ")

# Download paper
print("Connecting to "+args.username+"@"+args.host)
child = pexpect.spawn("ssh "+args.username+"@"+args.host)
child.expect('.*password: ')
child.sendline(password)
response = child.expect(['.*> ','\r\nPermission denied'])
if response==1:
	print("Permission denied")
	exit()
print("Downloading "+association+" paper #"+paper_id)
child.sendline('wget "http://ieeexplore.ieee.org/stampPDF/getPDF.jsp?tp=&isnumber=&arnumber="'+paper_id+' -O '+paper_name)
child.expect('.* saved .*')
child.sendline("exit")

# Copy paper back
print("Copying paper back")
child = pexpect.spawn("scp "+args.username+"@"+args.host+":"+paper_name+" .")
child.expect('.*password: ')
child.sendline(password)
child.expect('.*100%.*')

# Open file
os.system('open '+paper_name)
